### ISSUE TITLE
JSX Transformer!

### ISSUE THREAD

**Issue by dcflow** [clayallsopp/react-native-remote-component#1]
Hi,

How did the transformed jsx end up with `(function main(React, require) {` at the top. 
Did you use Babel?

Thank You!

**Comment by clayallsopp** [comment]
@DHidee66 yup, used Babel - you can try out an example here: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=(function(React%2C%20require)%20%7B%0A%20%20class%20A%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20A%0A%7D)

**Comment by dcflow** [comment]
Great :) Thank you
